name: Sphinx Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'  # Trigger only if changes are made in the 'docs' folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install sphinx_rtd_theme
          pip install sphinx_tabs

      - name: Build and Publish Documentation
        run: |
          cd docs
          make html



  deploy:
    runs-on: ubuntu-latest

    needs: build  # This ensures the 'deploy' job runs only if the 'build' job succeeds.

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html  # Adjust this based on your Sphinx output directory

