name: Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install sphinx_rtd_theme
          pip install sphinx_tabs

      - name: Build Documentation
        run: |
          cd docs
          pwd
          make html
          ls -la build/html  # Add this line to list the files in the build directory

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Files in Publish Directory
        run: |
          pwd
          ls -R
          ls -la build/html  # Add this line to list the files in the publish directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
          publish_branch: gh-pages
